name: main
description: "A new Flutter package project."

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  gap: ^3.0.1
  freezed_annotation: ^2.4.1
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3  
  feedback: ^3.0.0
  count:
    path: '../../feature/count'
  model:
    path: '../../core/model'
  ui:
    path: '../../core/ui'  
  download: 
    path: ../../feature/download

dev_dependencies:
  build_runner: ^2.4.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.4.6
  source_gen: ^1.5.0
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.8
  riverpod_lint: ^2.3.7
  testing:
    path: '../../core/testing'
