name: count
description: "A new Flutter package project."

environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  model:
    path: '../../core/model'
  importer:
    path: '../../importer'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
